# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-28 12:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20170228_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='oponent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oponent', to=settings.AUTH_USER_MODEL),
        ),
    ]
