# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-04 20:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_auto_20170228_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='cas_pridania',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='document',
            name='dokument',
            field=models.FileField(upload_to='projekty/%Y/<built-in function id>'),
        ),
    ]
