# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-04 21:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_auto_20170304_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='popis',
        ),
    ]
