# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-04 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_remove_document_popis'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='nazov_projektu',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='document',
            name='dokument',
            field=models.FileField(upload_to='projekty/%Y/<django.db.models.fields.CharField>'),
        ),
    ]
