# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-13 17:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_auto_20170304_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='nazov_projektu',
        ),
        migrations.AlterField(
            model_name='document',
            name='dokument',
            field=models.FileField(upload_to='projekty/%Y/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='document',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document', to='database.Document'),
        ),
    ]
